Plumbing.MVC/Models/ErrorViewModel.cs
namespace Plumbing.MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Plumbing.MVC/Areas/Admin/Controllers/AboutController.cs
using EntityLayer.WebApp.ViewModels.About;
using Microsoft.AspNetCore.Mvc;
using ServieceLayer.Serviecs.Abstract;

namespace Plumbing.MVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AboutController : Controller
    {
        private readonly IAboutService _aboutService;
        public AboutController(IAboutService aboutService)
        {
            _aboutService = aboutService;
        }
      

        public async Task<IActionResult> GetAboutList()
        {
            var aboutList = await _aboutService.GetAllListAsync();
            return View(aboutList);
        }

        [HttpGet]
        public async Task<IActionResult> AddAbout()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddAbout(AboutAddVM model)
        {
            await _aboutService.AddAboutAsync(model);
            return RedirectToAction(nameof(GetAboutList), "About", new { Area = "Admin" });
        }

        [HttpGet]
        public async Task<IActionResult> UpdateAbout(int Id)
        {
            var about = await _aboutService.GetByIdAsync(Id);

            return View(about);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateAbout(AboutUpdateVM model)
        {
            await _aboutService.UpdateAboutAsync(model);
            return RedirectToAction(nameof(GetAboutList), "About", new { Area = "Admin" });
        }


        public async Task<IActionResult> DeleteAbout(int Id)
        {
            await _aboutService.DeleteAboutAsync(Id);
            return RedirectToAction(nameof(GetAboutList), "About", new { Area = "Admin" });
        }
    }
}

Plumbing.MVC/Areas/Admin/Controllers/CategoryController.cs
using EntityLayer.WebApp.ViewModels.Category;
using Microsoft.AspNetCore.Mvc;
using ServieceLayer.Serviecs.Abstract;

namespace Plumbing.MVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {

        private readonly ICategoryService _categoryService;
        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public async Task<IActionResult> GetCategoryList()
        {
            var categoryList = await _categoryService.GetAllListAsync();
            return View(categoryList);
        }

        [HttpGet]
        public IActionResult AddCategory()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddCategory(CategoryAddMV model)
        {

            await _categoryService.AddCategoryAsync(model);
            return RedirectToAction(nameof(GetCategoryList), "Category", new { Area = "Admin" });
        }

        [HttpGet]
        public async Task<IActionResult> UpdateCategory(int Id)
        {
            var category = await _categoryService.GetByIdAsync(Id);

            return View(category);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateCategory(CategoryUpdateMV model)
        {
            await _categoryService.UpdateCategoryAsync(model);
            return RedirectToAction(nameof(GetCategoryList), "Category", new { Area = "Admin" });
        }

        public async Task<IActionResult> DeleteCategory(int Id)
        {
            await _categoryService.DeleteCategoryAsync(Id);
            return RedirectToAction(nameof(GetCategoryList), "Category", new { Area = "Admin" });
        }
    }
}

Plumbing.MVC/Areas/Admin/Controllers/ContactController.cs
using EntityLayer.WebApp.ViewModels.Contact;
using Microsoft.AspNetCore.Mvc;
using ServieceLayer.Serviecs.Abstract;

namespace Plumbing.MVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ContactController : Controller
    {
        private readonly IContactService _contactService;
        public ContactController(IContactService contactService)
        {
            _contactService = contactService;
        }

        public async Task<IActionResult> GetContactList()
        {
            var contactList = await _contactService.GetAllListAsync();
            return View(contactList);
        }

        [HttpGet]
        public async Task<IActionResult> AddContact()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddContact(ContactAddMV model)
        {
            await _contactService.AddContactAsync(model);
            return RedirectToAction(nameof(GetContactList), "Contact", new { Area = "Admin" });
        }

        [HttpGet]
        public async Task<IActionResult> UpdateContact(int Id)
        {
            var contact = await _contactService.GetByIdAsync(Id);

            return View(contact);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateContact(ContactUpdateMV model)
        {
            await _contactService.UpdateContactAsync(model);
            return RedirectToAction(nameof(GetContactList), "Contact", new { Area = "Admin" });
        }


        public async Task<IActionResult> DeleteContact(int Id)
        {
            await _contactService.DeleteContactAsync(Id);
            return RedirectToAction(nameof(GetContactList), "Contact", new { Area = "Admin" });
        }
    }
}

Plumbing.MVC/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace Plumbing.MVC.Areas.Admin.Controllers
{
    public class DashboardController : Controller
    {
        [Area("Admin")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

Plumbing.MVC/Controllers/AboutController.cs
using EntityLayer.WebApp.ViewModels.About;
using Microsoft.AspNetCore.Mvc;
using ServieceLayer.Serviecs.Abstract;

namespace Plumbing.MVC.Controllers
{
    public class AboutController : Controller
    {
        private readonly IAboutService _aboutService;

        public AboutController(IAboutService aboutService)
        {
            _aboutService = aboutService;
        }

        public async Task<IActionResult> GetAboutList()
        {
            var aboutList = await _aboutService.GetAllListAsync();
            return View(aboutList);
        }

        [HttpGet]
        public async Task<IActionResult> AddAbout()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddAbout(AboutAddVM model)
        {
            await _aboutService.AddAboutAsync(model);
            return RedirectToAction("GetAboutList", "AboutController", new { Area = "Admin" });
        }

        [HttpGet]
        public async Task<IActionResult> UpdateAbout(int Id)
        {
            var about = _aboutService.GetByIdAsync(Id);

            return View(about);
        }
        [HttpPost]
        public async Task<IActionResult> AddAbout(AboutUpdateVM model)
        {
            await _aboutService.UpdateAboutAsync(model);
            return RedirectToAction("GetAboutList", "AboutController", new { Area = "Admin" });
        }

        public async Task<IActionResult> DeleteAbout(int Id)
        {
            await _aboutService.DeleteAboutAsync(Id);
            return RedirectToAction("GetAboutList", "AboutController", new { Area = "Admin" });
        }
    }
}

Plumbing.MVC/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Plumbing.MVC.Models;

namespace Plumbing.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Plumbing.MVC/Areas/Admin/Views/About/AddAbout.cshtml
@model AboutAddVM
@{
    ViewData["Title"] = "AddAbout";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div>
    <h5 class="card-title">Add New About Us</h5>

    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Dashboard" asp-action="Index">Dashboard</a></li>
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="About" asp-action="GetAboutList">About Us</a></li>
            <li class="breadcrumb-item active">Add</li>
        </ol>
    </nav>
</div>

<div class="card">
    <div class="card-body pt-3">
        <form asp-area="Admin" asp-controller="About" asp-action="AddAbout" method="post" class="row g-3" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="FileName" value="test"/>
            <input type="hidden" asp-for="FileType" value="test"/>

            <div class="col-md-12">
                <div class="form-floating">
                    <input asp-for="Header" type="text" class="form-control" placeholder="Header">
                    <label asp-for="Header">Header</label>
                    <span asp-validation-for="Header" class="text-danger"></span>
                </div>
            </div>

            <div class="col-md-12">
                <div class="form-floating">
                    <textarea asp-for="Description" type="text" class="form-control" placeholder="Description"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                    <label asp-for="Description">Description</label>
                </div>
            </div>

            <div class="col-md-3">
                <div class="form-floating">
                    <input asp-for="Clients" type="number" class="form-control" placeholder="Clients">
                    <span asp-validation-for="Clients" class="text-danger"></span>
                    <label asp-for="Clients">Clients</label>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-floating">
                    <input asp-for="HoursOfSupport" type="number" class="form-control" placeholder="Hours Of Support">
                    <span asp-validation-for="HoursOfSupport" class="text-danger"></span>
                    <label asp-for="HoursOfSupport">Hours Of Support</label>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-floating">
                    <input asp-for="HardWorkers" type="number" class="form-control" placeholder="HardWorkers">
                    <span asp-validation-for="HardWorkers" class="text-danger"></span>
                    <label asp-for="HardWorkers">HardWorkers</label>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-floating">
                    <input asp-for="Projects" type="number" class="form-control" placeholder="Projects">
                    <span asp-validation-for="Projects" class="text-danger"></span>
                    <label asp-for="Projects">Projects</label>
                </div>
            </div>

            <div class="col-md-3">
                <div class="form-floating">
                    <input asp-for="SocialMedia.Facebook" type="text" class="form-control" placeholder="Facebook">
                    <span asp-validation-for="SocialMedia.Facebook" class="text-danger"></span>
                    <label asp-for="SocialMedia.Facebook">Facebook</label>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-floating">
                    <input asp-for="SocialMedia.Instagram" type="text" class="form-control" placeholder="Instagram">
                    <span asp-validation-for="SocialMedia.Instagram" class="text-danger"></span>
                    <label asp-for="SocialMedia.Instagram">Instagram</label>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-floating">
                    <input asp-for="SocialMedia.Twitter" type="text" class="form-control" placeholder="Twitter">
                    <span asp-validation-for="SocialMedia.Twitter" class="text-danger"></span>
                    <label asp-for="SocialMedia.Twitter">Twitter</label>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-floating">
                    <input asp-for="SocialMedia.LinkedIn" type="text" class="form-control" placeholder="LinkedIn">
                    <span asp-validation-for="SocialMedia.LinkedIn" class="text-danger"></span>
                    <label asp-for="SocialMedia.LinkedIn">LinkedIn</label>
                </div>
            </div>

            <div class="col-md-12">
                <div class="form-floating">
                    <input asp-for="Photo" accept="image/*" type="file" class="form-control" placeholder="Photo">
                   
                </div>
            </div>

            <div class="text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
                <button type="reset" class="btn btn-secondary">Reset</button>
            </div>
        </form>
    </div>
</div>

Plumbing.MVC/Areas/Admin/Views/About/GetAboutList.cshtml
@model List<AboutListMV>
@{
    ViewData["Title"] = "GetAboutList";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<h5 class="card-title">About Us</h5>

<nav>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Dashboard" asp-action="Index">Dashboard</a></li>
        <li class="breadcrumb-item active">About US</li>
    </ol>
</nav>

<div class="card">
<div class="card-body">

    <!-- Table with hoverable rows -->
    <table class="table table-hover">
        <thead>
            <tr>
                
                <th scope="col">Header</th>
                <th scope="col">Created Date</th>
                <th scope="col">Updated Date</th>
                <th scope="col">Delete</th>
                
            </tr>
        </thead>
        <tbody>
          
           @foreach (var item in Model)
            {
                    <tr>
                        <td>@item.Header</td>
                        <td>@item.CreatedAt</td>
                        <td>@item.UpdatedAt</td>
                        <td><a asp-area="Admin" asp-controller="About" asp-action="DeleteAbout" asp-route-id="@item.Id" data-id ="@item.Id" class="btn btn-danger btn-sm"> Delete</a></td>

                    </tr>
            }
        </tbody>
    </table>
       @foreach(var item in Model)
        {
            <section class="section profile">
                <div class="row">
                    <div class="col-xl-4">

                        <div class="card">
                            <div class="card-body profile-card pt-4 d-flex flex-column align-items-center">

                                <img src="@item.FileName" alt="Profile" class="rounded-circle">
                                <div class="social-links mt-2">
                                    <a href="@item.SocialMedia.Twitter" class="twitter"><i class="bi bi-twitter"></i></a>
                                    <a href="@item.SocialMedia.Facebook" class="facebook"><i class="bi bi-facebook"></i></a>
                                    <a href="@item.SocialMedia.Instagram" class="instagram"><i class="bi bi-instagram"></i></a>
                                    <a href="@item.SocialMedia.LinkedIn" class="linkedin"><i class="bi bi-linkedin"></i></a>
                                </div>
                            </div>
                        </div>

                    </div>

                    <div class="col-xl-8">

                        <div class="card">
                            <div class="card-body pt-3">
                                <!-- Bordered Tabs -->

                                <div class="tab-content pt-2">


                                    <div class="tab-pane fade show active profile-overview" id="profile-overview">
                                        <h5 class="card-title">About Us</h5>
                                        <p class="small fst-italic">@item.Description</p>

                                        <h5 class="card-title">Profile Details</h5>

                                        <div class="row">
                                            <div class="col-lg-3 col-md-4 label ">Header</div>
                                            <div class="col-lg-9 col-md-8">@item.Header</div>
                                        </div>

                                        <div class="row">
                                            <div class="col-lg-3 col-md-4 label">Clients</div>
                                            <div class="col-lg-9 col-md-8">@item.Clients</div>
                                        </div>

                                        <div class="row">
                                            <div class="col-lg-3 col-md-4 label">Projects</div>
                                            <div class="col-lg-9 col-md-8">@item.Projects</div>
                                        </div>

                                        <div class="row">
                                            <div class="col-lg-3 col-md-4 label">Hours Of Support</div>
                                            <div class="col-lg-9 col-md-8">@item.HoursOfSupport</div>
                                        </div>

                                        <div class="row">
                                            <div class="col-lg-3 col-md-4 label">Hard Workers</div>
                                            <div class="col-lg-9 col-md-8">@item.HardWorkers</div>
                                        </div>

                                        <a asp-area="Admin" asp-controller="About" asp-action="UpdateAbout" asp-route-id="@item.Id" data-id="@item.Id" class="btn btn-primary">Edit Profile</a>
                                    </div>



                                </div><!-- End Bordered Tabs -->

                            </div>
                        </div>

                    </div>
                </div>
            </section>
        }
        <!-- End Table with hoverable rows -->
        
</div>
</div>

<td><a asp-area="Admin" asp-controller="About" asp-action="AddAbout" class="btn btn-success btn-sm"> Add About Us</a></td>

Plumbing.MVC/Areas/Admin/Views/About/UpdateAbout.cshtml
@model AboutUpdateVM
@{
    ViewData["Title"] = "UpdateAbout";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div>
    <h5 class="card-title">Update About Us</h5>

    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Dashboard" asp-action="Index">Dashboard</a></li>
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="About" asp-action="GetAboutList">About Us</a></li>
            <li class="breadcrumb-item active">Update</li>
        </ol>
    </nav>
</div>

<div class="card">
    <div class="card-body pt-3">
        <form asp-area="Admin" asp-controller="About" asp-action="UpdateAbout" method="post" class="row g-3" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="RowVersion" />
            <input type="hidden" asp-for="FileName" value="test" />
            <input type="hidden" asp-for="FileType" value="test" />

            <div class="col-md-12">
                <div class="form-floating">
                    <input asp-for="Header" type="text" class="form-control" placeholder="Header">
                    <label asp-for="Header">Header</label>
                    <span asp-validation-for="Header" class="text-danger"></span>
                </div>
            </div>

            <div class="col-md-12">
                <div class="form-floating">
                    <textarea asp-for="Description" type="text" class="form-control" placeholder="Description"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                    <label asp-for="Description">Description</label>
                </div>
            </div>

            <div class="col-md-3">
                <div class="form-floating">
                    <input asp-for="Clients" type="number" class="form-control" placeholder="Clients">
                    <span asp-validation-for="Clients" class="text-danger"></span>
                    <label asp-for="Clients">Clients</label>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-floating">
                    <input asp-for="HoursOfSupport" type="number" class="form-control" placeholder="Hours Of Support">
                    <span asp-validation-for="HoursOfSupport" class="text-danger"></span>
                    <label asp-for="HoursOfSupport">Hours Of Support</label>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-floating">
                    <input asp-for="HardWorkers" type="number" class="form-control" placeholder="HardWorkers">
                    <span asp-validation-for="HardWorkers" class="text-danger"></span>
                    <label asp-for="HardWorkers">HardWorkers</label>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-floating">
                    <input asp-for="Projects" type="number" class="form-control" placeholder="Projects">
                    <span asp-validation-for="Projects" class="text-danger"></span>
                    <label asp-for="Projects">Projects</label>
                </div>
            </div>

            <partial name="UpdateSocialMediaPartialView/_SocialMediaView" />


            <div class="col-md-12">
                <div class="form-floating">
                    <input asp-for="Photo" accept="image/*" type="file" class="form-control" placeholder="Photo">

                </div>
            </div>

            <div class="text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
                <button type="reset" class="btn btn-secondary">Reset</button>
            </div>
        </form>
    </div>
</div>

Plumbing.MVC/Areas/Admin/Views/Category/AddCategory.cshtml
@model CategoryAddMV
@{
    ViewData["Title"] = "AddCategory";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div>
    <h5 class="card-title">Add New Category</h5>

    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Dashboard" asp-action="Index">Dashboard</a></li>
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Category" asp-action="GetCategoryList">Category</a></li>
            <li class="breadcrumb-item active">Add</li>
        </ol>
    </nav>
</div>

<div class="card">
    <div class="card-body pt-3">
        <form asp-area="Admin" asp-controller="Category" asp-action="AddCategory" method="post" class="row g-3">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            

            <div class="col-md-12">
                <div class="form-floating">
                    <input asp-for="Name" type="text" class="form-control" placeholder="Name">
                    <label asp-for="Name">Name</label>
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>

   
            <div class="text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
                <button type="reset" class="btn btn-secondary">Reset</button>
            </div>
        </form>
    </div>
</div>

Plumbing.MVC/Areas/Admin/Views/Category/UpdateCategory.cshtml
@model CategoryUpdateMV
@{
    ViewData["Title"] = "UpdateCategory";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div>
    <h5 class="card-title">Update Category</h5>

    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Dashboard" asp-action="Index">Dashboard</a></li>
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Category" asp-action="GetCategoryList">Category</a></li>
            <li class="breadcrumb-item active">Update</li>
        </ol>
    </nav>
</div>

<div class="card">
    <div class="card-body pt-3">
        <form asp-area="Admin" asp-controller="Category" asp-action="UpdateCategory" method="post" class="row g-3">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="RowVersion" />


            <div class="col-md-12">
                <div class="form-floating">
                    <input asp-for="Name" type="text" class="form-control" placeholder="Name">
                    <label asp-for="Name">Name</label>
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>


            <div class="text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
                <button type="reset" class="btn btn-secondary">Reset</button>
            </div>
        </form>
    </div>
</div>

Plumbing.MVC/Areas/Admin/Views/Contact/AddContact.cshtml
@model ContactAddMV
@{
    ViewData["Title"] = "AddContact";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div>
    <h5 class="card-title">Add New Contact</h5>

    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Dashboard" asp-action="Index">Dashboard</a></li>
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Contact" asp-action="GetContactList">Contact</a></li>
            <li class="breadcrumb-item active">Add</li>
        </ol>
    </nav>
</div>

<div class="card">
    <div class="card-body pt-3">

        <form asp-area="Admin" asp-controller="Contact" asp-action="AddContact" method="post" class="row g-3">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="col-md-12">
                <div class="form-floating">
                    <input asp-for="Location" type="text" class="form-control" placeholder="Location">
                    <label asp-for="Location">Location</label>
                    <span asp-validation-for="Location" class="text-danger"></span>
                </div>
            </div>

            <div class="col-md-12">
                <div class="form-floating">
                    <input asp-for="Email" type="email" class="form-control" placeholder="Email">
                    <label asp-for="Email">Email</label>
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
            </div>

            <div class="col-md-12">
                <div class="form-floating">
                    <input asp-for="Call" type="tel" class="form-control" placeholder="Call">
                    <label asp-for="Call">Call</label>
                    <span asp-validation-for="Call" class="text-danger"></span>
                </div>
            </div>

            <div class="col-md-12">
                <div class="form-floating">
                    <input asp-for="Map" type="url" class="form-control" placeholder="Map">
                    <label asp-for="Map">Map Link</label>
                    <span asp-validation-for="Map" class="text-danger"></span>
                </div>
            </div>


            <div class="text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
                <button type="reset" class="btn btn-secondary">Reset</button>
            </div>
        </form>
    </div>
</div>

Plumbing.MVC/Areas/Admin/Views/Contact/GetContactList.cshtml
@model List<ContactListMV>
@{
    ViewData["Title"] = "GetContactList";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h5 class="card-title"> Contact Information</h5>

<nav>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Dashboard" asp-action="Index">Dashboard</a></li>
        <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Contact" asp-action="GetContactList">Contact</a></li>
    </ol>
</nav>

<div class="card">
    <div class="card-body">

        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Location</th>
                    <th scope="col">Email</th>
                    <th scope="col">Call</th>
                    <th scope="col">Map Link</th>
                    <th scope="col">Created Date</th>
                    <th scope="col">Updated Date</th>
                    <th scope="col">Edit</th>
                    <th scope="col">Delete</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Location</td>
                        <td>@item.Email</td>
                        <td>@item.Call</td>
                        @if(!string.IsNullOrEmpty(item.Map))
                        {
                            <td>Assigned</td>
                        }
                        else
                        {
                            <td>Not Assigned</td>
						}
                        <td>@item.CreatedAt</td>
                        <td>@item.UpdatedAt</td>

                        <td>
                            <a asp-area="Admin" asp-controller="Contact" asp-action="UpdateContact" asp-route-id="@item.Id" data-id="@item.Id" class="btn btn-warning btn-sm"> Edit</a>
                        </td>
                        <td>
                            <a asp-area="Admin" asp-controller="Contact" asp-action="DeleteContact" asp-route-id="@item.Id" data-id="@item.Id" class="btn btn-danger btn-sm"> Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

        <div>
            <a asp-area="Admin" asp-controller="Contact" asp-action="AddContact" class="btn btn-success btn-sm"> Add Contact</a>
        </div>

    </div>
</div>

Plumbing.MVC/Areas/Admin/Views/Dashboard/index.cshtml
@{
    ViewData["Title"] = "index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>Dashboard</h1>

Plumbing.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>